site_name: FusedVR Chain Auth
site_url: https://fusedvr.github.io/chainauth-docs/
theme: readthedocs
docs_dir: documentation
site_dir: site
nav:
  - 'docs/index.md'
  - Get Started : 'docs/get-started/index.md'
  - Contribute to the Docs: 'docs/contribution/index.md'
  - "Tutorials":
    - Unity SDK Guide : 'docs/tutorials/unitysdk.md'
    - NFT Tickets for Games : 'docs/tutorials/nftgame.md'
  - "Resources":
    - FusedVR Crypto APIs : 'https://api-crypto.fusedvr.com'
    - FusedVR Unity SDK : 'https://github.com/FusedVR/web3-unity-sdk'
    - FusedVR Code Link : "https://link.fusedvr.com"

